# Game settings
MAX_BOMBS = 2
BOMB_REPAIRING = 5
BOMB_MINIMAL_CASUALTY = 10
BOMB_MULTIPLIER = 2
MAX_DISTANCE = 20

# Strategy settings
BOMB_PROHIBITION = 2

# Owners
ENEMY = -1
NEUTRAL = 0
MY = 1

FACTORY_ENTITY = 'FACTORY'
TROOP_ENTITY = 'TROOP'
BOMB_ENTITY = 'BOMB'
